services:

  # Everything is run from this container instead of the host machine.
  # If you need some core dependencies or any custom install, just modify the Dockerfile.devEnv file.
  dev-env:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile.devEnv
      args:
        - NODE_VERSION=${NODE_VERSION}
    volumes:
      - ../..:/image-server/infrastructure:delegated
      - ../../../app/dist:/image-server/app/dist:ro
      - volume-pnpm-store:/image-server/infrastructure/.pnpm-store
      - volume-aws-credentials:/root/.aws
    working_dir: /image-server/infrastructure
    env_file:
      - ../../.env
    command: bash

volumes:
  volume-pnpm-store: 
  volume-aws-credentials:
